### ISSUE TITLE
Component 2.0

### ISSUE THREAD

**Issue by ghost** [sankargorthi/component-server#1]
Component 2.0 is considering a new registry:

https://github.com/component/component/issues/429

They're planning private registry support. Need to keep an eye on this.

**Comment by sankargorthi** [comment]
Absolutely. I need this right now for my repository at work. Will move to the registry whenever possible.

Whenever the registry is available, I intend to deprecate this repo and point to the registry setup instructions. Specifically to instructions for setting up private registries.

**Comment by ghost** [comment]
Yeah, same here. I like the plan. 

Maybe we can even help out @visionmedia & co. with the registry implementation if we're able.
